services:
  api-petfoster:
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html # Permet le montage du dossier public
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # Montée des certificats SSL depuis l'hôte
    depends_on:
      - api-petfoster
    restart: always
