networks:
  nodejs:
    driver: bridge

services:
  # Postgres Service
  pg-petfoster:
    image: postgres:16.3-alpine3.20
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./doc/data/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    networks:
      - nodejs
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5

  # Backend Service
  api-petfoster:
    image: node:lts-alpine3.20
    volumes:
      - .:/src
    working_dir: /src
    networks:
      - nodejs
    depends_on:
      pg-petfoster:
        condition: service_healthy

    expose:
      - "5050"
    ports:
      - "5050:5050"
    command: ["sh", "-c", "npm install && npm run dev --host 0.0.0.0"]
    env_file:
      - .env
